### ISSUE TITLE
metadata changed event key must be optional

### ISSUE THREAD

**Issue by saivert** [arcnmx/wireplumber.rs#33] opened 2023-09-16 21:15 UTC
changed event is emitted with key == NULL when a metadata item is removed.

see https://gitlab.freedesktop.org/pipewire/wireplumber/-/blob/ca58c68ef988e57f5bec232fe6c9ab86d5f0ea19/lib/wp/metadata.c#L218

Though I'm moving to using closure_local macro which makes me get at the event arguments directly instead of via GValue.

```rust
let changed_closure = closure_local!(@watch widget =>
                        move |_obj: &wp::pw::Metadata, id: u32, key: Option<String>, _type: Option<String>, _value: Option<String>| {
                        let key = key.unwrap_or_default();
                        if id == boundid && key.contains("target.") {
                            wp::log::info!("metadata changed handler id: {boundid} {key:?} {_value:?}!");
                            widget.update_output_device_dropdown();
                        }
                    });
                    metadata.connect_closure("changed", false, changed_closure);
```

**Comment by arcnmx** [comment] 2023-09-16 23:01
This sounds like a duplicate of #30, was it not fixed by 95c55499881dea199a1c62f755f35b9e7c1b2fb0? What code reproduces the issue?

**Comment by saivert** [comment] 2023-09-17 07:01
Yes, it was partly fixed then but id key also has to be Optional.

**Comment by arcnmx** [comment] 2023-09-18 01:10
Gotcha, `p0` was missed in that fix, thanks for the clarification!

**Closed** 2023-09-18 16:03 UTC
